---

name: "Kubernetes resources removal"

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      confirm_destroy_repository_name:
        description: 'Confirm that you want to delete the Kubernetes resources introducing the <repository name>'
        type: string
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TF_LOG: ${{ vars.TF_LOG }}

jobs:
  terraform:
    name: "Kubernetes resources removal"
    if: ${{ inputs.confirm_destroy_repository_name == github.event.repository.name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3.5.3

      - name: Set environment variables
        working-directory: ./
        run: |
          SUFFIX_NAME=$(sed -n -E "s/[[:space:]]*(bucket_suffix_name\:)[[:space:]]*(.*)/\2/1p" < configuration.yml)
          echo "TF_BUCKET=${{ env.AWS_ACCOUNT_ID }}-${{ env.AWS_DEFAULT_REGION }}-$SUFFIX_NAME" >> $GITHUB_ENV
          echo "TF_KEY=$(basename $(pwd)).tfstate" >> $GITHUB_ENV


      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.5.1

      - name: Terraform init
        id: init
        run: |
          terraform init -lockfile=readonly
            -backend-config="bucket=${{ env.TF_BUCKET }}" \
            -backend-config="key=${{ env.TF_KEY }}" \
            -backend-config="region=${{ vars.AWS_DEFAULT_REGION }}"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check -diff

      - name: Terraform validate
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        id: validate
        run: terraform validate

      - name: Terraform plan destroy
        id: plan
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: terraform plan -destroy -no-color -input=false
        continue-on-error: true

      - name: Terraform Plan Status
        id: status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Destroy
        id: destroy
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: terraform destroy -no-color -auto-approve -input=false
